# Generated by Django 5.2.8 on 2025-11-09 12:23

import extentions.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email_address', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('message', models.TextField(verbose_name='Message')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read?')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DegreeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=extentions.utils.degree_image_path, verbose_name='Image')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('created', models.DateField(verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Degree',
                'verbose_name_plural': 'Degrees',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to=extentions.utils.user_image_path, verbose_name='Profile')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('ln', models.CharField(max_length=255, verbose_name='LinkedIn')),
                ('insta', models.CharField(max_length=255, verbose_name='Instagram')),
                ('github', models.CharField(max_length=255, verbose_name='GitHub')),
                ('telegram', models.CharField(max_length=255, verbose_name='Telegram')),
                ('phone', models.PositiveBigIntegerField(verbose_name='Phone Number')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Information',
                'verbose_name_plural': 'Informations',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=extentions.utils.portfolio_image_path, verbose_name='Image')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('techs', models.CharField(max_length=255, verbose_name='Technologies')),
                ('description', models.TextField(verbose_name='Description')),
                ('created', models.DateField(verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255, verbose_name='Skill')),
                ('percent', models.PositiveIntegerField(verbose_name='Percent')),
                ('title', models.CharField(choices=[('beginner', 'BEGINNER'), ('expert', 'EXPERT'), ('master', 'MASTER'), ('advance', 'ADVANCE')], max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
    ]
