# Generated by Django 5.2.8 on 2025-11-09 17:14

import extentions.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('github', models.CharField(max_length=255, verbose_name='GitHub')),
                ('version', models.CharField(max_length=255, verbose_name='Last Version')),
                ('image', models.ImageField(upload_to=extentions.utils.package_image_path, verbose_name='Image')),
                ('desc', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['-id'],
            },
        ),
    ]
