# Generated by Django 5.2.8 on 2025-11-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contactmodel_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='ip',
            field=models.CharField(blank=True, max_length=50, verbose_name='user IP'),
        ),
    ]
